# Generated by Django 4.2.1 on 2023-05-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productsimage_popularproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularproductsimage',
            name='popularproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.popularproduct'),
        ),
    ]
